# Introdução a Python

## Aula 6

# Sumário

- Instalação e setup
- Módulo NumPy

# Instalação e setup

[![](https://img.shields.io/badge/Jupyter-ffffff?style=for-the-badge&logo=jupyter)](https://jupyter.org/install)

[![](https://img.shields.io/badge/NumPy-4c78d0?style=for-the-badge&logo=numpy)](https://numpy.org/install/)

# Módulo NumPy

Para importar o módulo

In [2]:
import numpy as np

Para verificar a respetiva versão

In [3]:
print(np.__version__)

1.20.1


## Criação de arrays

In [19]:
array0d = np.array(1) #poderia ser passado qualquer outro objeto semelhante a um array

print(array0d)

1


In [20]:
array1d = np.array([1,2,3]) 

print(array1d)

[1 2 3]


In [21]:
array2d = np.array([[1,2,3], [4,5,6]])

print(array2d)

[[1 2 3]
 [4 5 6]]


In [22]:
array3d = np.array([[[1,2,3], [4,5,6], [7,8,9]]])

print(array3d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [30]:
array5d = np.array([1,2,3], ndmin=5)

print(array5d.ndim)

5


## Indexação de arrays

In [27]:
pairs = np.array([2,4,6])

pairs[0]

2

In [33]:
even_odd = np.array([[2,4,6],[1,3,5]])

even_odd[1, 1]

3

In [46]:
powers_of_3 = np.array([1,3,9,27])

powers_of_3[-2]

9

In [52]:
multiples_of_2_3 = np.array([[2,4,6],[3,6,9]])

multiples_of_2_3[1, -3]

3

In [40]:
primes = np.array([2, 3, 5, 7])

primes[1:3]

array([3, 5])

In [53]:
divisors_of_6_8 = np.array([[1, 2, 3, 6], [1, 2, 4, 8]]) 

divisors_of_6_8[1, 1:4]

array([2, 4, 8])

In [45]:
powers_of_2 = np.array([1,2,4,8])

powers_of_2[-3:-1]

array([2, 4])

In [51]:
negative_positive = np.array([[-1,-2,-3,-4], [1,2,3,4]])

negative_positive[0, -4:-2]

array([-1, -2])

In [43]:
multiples_of_5 = np.array([5,10,15,20])

multiples_of_5[1:]

array([10, 15, 20])

In [54]:
int_float = np.array([[1,2,3,4],[1.1,2.2,3.3,4.4]])

int_float[1, 2:]

array([3.3, 4.4])

In [49]:
perfect_squares = np.array([1,4,9,16,25])

perfect_squares[:2]

array([1, 4])

In [58]:
end_in_4_8 = np.array([[4,14,24,34],[8,18,28,38]])

end_in_4_8[0, :3]

array([ 4, 14, 24])

In [59]:
decimal_places_1_2 = np.array([[1.1, 1.2, 1.3], [1.11, 1.22, 1.33]])

decimal_places_1_2[0:2, 2]

array([1.3 , 1.33])

In [60]:
start_in_2_6 = np.array([[2,20,21,22], [6,60,61,62]])

start_in_2_6[0:2, 1:3]

array([[20, 21],
       [60, 61]])

## Tipos

`S`: string

`i`: integer

`f`: float

`c`: complex

`b`: boolean

## Copy vs View

In [63]:
repeated = np.array([2,2,2,2])

copy_repeated = repeated.copy()

repeated[0] = -2

print(repeated)
print(copy_repeated)

[-2  2  2  2]
[2 2 2 2]


In [65]:
numbers_1_to_5 = np.array([1,2,3,4,5])

view_numbers_1_to_5 = numbers_1_to_5.view()

numbers_1_to_5[0] = 0

print(numbers_1_to_5)
print(view_numbers_1_to_5)

[0 2 3 4 5]
[0 2 3 4 5]


In [66]:
ones = np.array([1,1,1,1,1])

copy_ones = ones.copy()
view_ones = ones.view()

print(copy_ones.base)
print(view_ones.base)

None
[1 1 1 1 1]


In [61]:
ascending_descending = np.array([[1,2,3,4], [4,3,2,1]])

ascending_descending.shape

(2, 4)

# Exercícios