# Introdução a Python

## Aula 6

# Sumário

- Instalação e setup
- Módulo NumPy

# Instalação e setup

[![](https://img.shields.io/badge/Jupyter-ffffff?style=for-the-badge&logo=jupyter)](https://jupyter.org/install)

[![](https://img.shields.io/badge/NumPy-4c78d0?style=for-the-badge&logo=numpy)](https://numpy.org/install/)

# Módulo NumPy

Para importar o módulo

In [1]:
import numpy as np

Para verificar a respetiva versão

In [3]:
print(np.__version__)

1.20.1


## Criação de arrays

In [19]:
array0d = np.array(1) #poderia ser passado qualquer outro objeto semelhante a um array

print(array0d)

1


In [20]:
array1d = np.array([1,2,3]) 

print(array1d)

[1 2 3]


In [21]:
array2d = np.array([[1,2,3], [4,5,6]])

print(array2d)

[[1 2 3]
 [4 5 6]]


In [22]:
array3d = np.array([[[1,2,3], [4,5,6], [7,8,9]]])

print(array3d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [30]:
array5d = np.array([1,2,3], ndmin=5)

print(array5d.ndim)

5


## Indexação de arrays

In [27]:
pairs = np.array([2,4,6])

pairs[0]

2

In [33]:
even_odd = np.array([[2,4,6],[1,3,5]])

even_odd[1, 1]

3

In [46]:
powers_of_3 = np.array([1,3,9,27])

powers_of_3[-2]

9

In [52]:
multiples_of_2_3 = np.array([[2,4,6],[3,6,9]])

multiples_of_2_3[1, -3]

3

In [40]:
primes = np.array([2, 3, 5, 7])

primes[1:3]

array([3, 5])

In [53]:
divisors_of_6_8 = np.array([[1, 2, 3, 6], [1, 2, 4, 8]]) 

divisors_of_6_8[1, 1:4]

array([2, 4, 8])

In [45]:
powers_of_2 = np.array([1,2,4,8])

powers_of_2[-3:-1]

array([2, 4])

In [51]:
negative_positive = np.array([[-1,-2,-3,-4], [1,2,3,4]])

negative_positive[0, -4:-2]

array([-1, -2])

In [43]:
multiples_of_5 = np.array([5,10,15,20])

multiples_of_5[1:]

array([10, 15, 20])

In [54]:
int_float = np.array([[1,2,3,4],[1.1,2.2,3.3,4.4]])

int_float[1, 2:]

array([3.3, 4.4])

In [49]:
perfect_squares = np.array([1,4,9,16,25])

perfect_squares[:2]

array([1, 4])

In [58]:
end_in_4_8 = np.array([[4,14,24,34],[8,18,28,38]])

end_in_4_8[0, :3]

array([ 4, 14, 24])

In [59]:
decimal_places_1_2 = np.array([[1.1, 1.2, 1.3], [1.11, 1.22, 1.33]])

decimal_places_1_2[0:2, 2]

array([1.3 , 1.33])

In [60]:
start_in_2_6 = np.array([[2,20,21,22], [6,60,61,62]])

start_in_2_6[0:2, 1:3]

array([[20, 21],
       [60, 61]])

## Tipos de dados

`S`: string

`i`: integer

`f`: float

`c`: complex

`b`: boolean

In [2]:
array_of_ints = np.array([1,2,3,4])

array_of_ints.dtype

dtype('int64')

In [5]:
array_of_strings = np.array([2,4,6,8], dtype = "S") #também poderíamos definir o tamanho

array_of_strings.dtype

dtype('S1')

In [9]:
string_to_int = np.array(["1", "2", "3"])

new_string_to_int = string_to_int.astype("i") #também poderíamos colocar int

new_string_to_int.dtype

dtype('int32')

## Copy vs View

In [63]:
repeated = np.array([2,2,2,2])

copy_repeated = repeated.copy()

repeated[0] = -2

print(repeated)
print(copy_repeated)

[-2  2  2  2]
[2 2 2 2]


In [65]:
numbers_1_to_5 = np.array([1,2,3,4,5])

view_numbers_1_to_5 = numbers_1_to_5.view()

numbers_1_to_5[0] = 0

print(numbers_1_to_5)
print(view_numbers_1_to_5)

[0 2 3 4 5]
[0 2 3 4 5]


In [66]:
ones = np.array([1,1,1,1,1])

copy_ones = ones.copy()
view_ones = ones.view()

print(copy_ones.base)
print(view_ones.base)

None
[1 1 1 1 1]


## Forma e remodelação de arrays

In [61]:
ascending_descending = np.array([[1,2,3,4], [4,3,2,1]])

ascending_descending.shape

(2, 4)

In [11]:
huge_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

new_huge_array = huge_array.reshape(4,3)

new_huge_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
dim1_to_dim3 = np.array([11,12,13,14,15,16,17,18,19,20,21,22])

new_dim1_to_dim3 = dim1_to_dim3.reshape(2,3,2)

new_dim1_to_dim3

array([[[11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22]]])

In [48]:
calculate_last_dimension = np.array([1,2,3,4,5,6,7,8])

new_calculate_last_dimension = calculate_last_dimension.reshape(2,2,-1)

new_calculate_last_dimension

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
separate_arrays = np.array([[3,6,7], [1,3,7]])

joint_arrays = separate_arrays.reshape(-1)

joint_arrays

array([3, 6, 7, 1, 3, 7])

## Iteração de arrays

In [20]:
high_dimensionality_array = np.array([[[[1,2],[3,4]], [[5,6], [7,8]]]])

for x in np.nditer(high_dimensionality_array):
    print(x)

1
2
3
4
5
6
7
8


In [23]:
array_of_chars = np.array([["a", "b", "c"], ["d", "e", "f"]])

for idx, x in np.ndenumerate(array_of_chars):
    print(idx, x)

(0, 0) a
(0, 1) b
(0, 2) c
(1, 0) d
(1, 1) e
(1, 2) f


## Junção de arrays

In [18]:
first_array = np.array([1,2,3])

second_array = np.array([4,5,6])

resulting_array = np.concatenate((first_array, second_array))

resulting_array

array([1, 2, 3, 4, 5, 6])

In [26]:
array1 = np.array([[1,2], [3,4]])

array2 = np.array([[5,6], [7,8]])

final_array = np.concatenate((array1, array2), axis = 1) #axis toma o valor 0 por omissão

final_array

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [38]:
top = np.array([6,7,8])
bottom = np.array([9,10,11])

top_and_bottom = np.stack((top, bottom))

top_and_bottom

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
top = np.array([6,7,8])
bottom = np.array([9,10,11])

top_and_bottom = np.vstack((top, bottom))

top_and_bottom

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
first = np.array([10,11,12])

second = np.array([13,14,15])

first_and_second = np.stack((first, second), axis=1)

first_and_second

array([[10, 13],
       [11, 14],
       [12, 15]])

In [42]:
first = np.array([10,11,12])

second = np.array([13,14,15])

first_and_second = np.dstack((first, second))

first_and_second

array([[[10, 13],
        [11, 14],
        [12, 15]]])

In [43]:
begin = np.array([10,9,8])

end = np.array([7,6,5])

begin_and_end = np.hstack((begin, end))

begin_and_end

array([10,  9,  8,  7,  6,  5])

## Separação de arrays

In [44]:
array_with_6_elems = np.array([1,2,3,4,5,6])

new_array_with_6_elems = np.array_split(array_with_6_elems,3)

new_array_with_6_elems

[array([1, 2]), array([3, 4]), array([5, 6])]

In [50]:
array_with_5_elems = np.array([1,2,3,4,5])

new_array_with_5_elems = np.array_split(array_with_5_elems, 4)

new_array_with_5_elems

[array([1, 2]), array([3]), array([4]), array([5])]

In [46]:
array_with_12_elems = np.array([[1,2], [3,4], [5,6], [7,8], [9,10], [11,12]])

new_array_with_12_elems = np.array_split(array_with_12_elems,3)

new_array_with_12_elems

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [21]:
array_with_10_elems = np.array([[1,2], [3,4], [5,6], [7,8], [9,10]])

new_array_with_10_elems = np.array_split(array_with_10_elems,4)

new_array_with_10_elems

[array([[1, 2],
        [3, 4]]),
 array([[5, 6]]),
 array([[7, 8]]),
 array([[ 9, 10]])]

## Pesquisa em arrays

In [29]:
array_with_repeated_elems = np.array([1,2,3,3,4,5,3])

positions = np.where(array_with_repeated_elems == 3) #para além da condição pode receber mais dois 
#argumentos x (que vai ser executado caso a condição seja verdadeira) e y (que vai ser executado 
#caso a condição seja falsa)

positions

(array([2, 3, 6]),)

In [32]:
initial_array = np.array([1,2,3,4])

position = np.searchsorted(initial_array, 2) #é suposto este método ser usado em arrays ordenados

position

1

In [33]:
initial_array = np.array([1,2,3,4])

index = np.searchsorted(initial_array, 2, side = "right")

index

2

In [34]:
starting_array = np.array([2,4,6,8])

indexes = np.searchsorted(starting_array, [1,3,5])

indexes

array([0, 1, 2])

## Ordenação de arrays

In [35]:
unordered_array = np.array([9,1,6,3,2])

np.sort(unordered_array) #também funciona para outros tipos de dados

array([1, 2, 3, 6, 9])

In [27]:
unordered_array_2d = np.array([[6,1,5], [5,9,1]])

np.sort(unordered_array_2d)

array([[1, 5, 6],
       [1, 5, 9]])

## Filtragem de arrays

In [37]:
array_from_10_to_15 = np.array([10,11,12,13,14,15])

booleans = [True, False, True, True, False, True]

filtered_array = array_from_10_to_15[booleans]

filtered_array

array([10, 12, 13, 15])

In [ ]:
# falta terminar

In [ ]:
# numpy.mat

In [7]:
first_addend = np.array([1,2,3,4])

second_addend = np.array([5,6,7,8])

result_addition = np.add(first_addend, second_addend)

result_addition

array([ 6,  8, 10, 12])

In [8]:
minuend = np.array([10,11,12])

subtrahend = np.array([5,4,3])

result_subtraction = np.subtract(minuend, subtrahend)

result_subtraction

array([5, 7, 9])

In [9]:
multiplicand = np.array([5,10,15])

multiplier = np.array([1,10,100])

result_multiplication = np.multiply(multiplicand, multiplier)

result_multiplication

array([   5,  100, 1500])

In [11]:
dividend = np.array([30,40,50])

divisor = np.array([3,20,2])

result_division = np.divide(dividend, divisor)

result_division

array([10.,  2., 25.])

In [12]:
base = np.array([2,3,4])

exponent = np.array([0,1,2])

result_power = np.power(base, exponent)

result_power

array([ 1,  3, 16])

In [13]:
dividend = np.array([10, 20, 30])

divisor = np.array([4,7,3])

remainder = np.remainder(dividend, divisor) #também poderíamos usar a função mod()

remainder

array([2, 6, 0])

In [15]:
dividend = np.array([10, 20, 30])

divisor = np.array([4,7,3])

result_divmod = np.divmod(dividend, divisor)

result_divmod

(array([ 2,  2, 10]), array([2, 6, 0]))

In [16]:
negative_values = np.array([-4,-5,-8])

absolute_values = np.absolute(negative_values) #também poderíamos usar a função abs()

absolute_values

array([4, 5, 8])

## Outras funções relevantes

- arange()

In [36]:
array_with_arange = np.arange(5, 10) #por omissão o primeiro argumento é 0

array_with_arange

array([5, 6, 7, 8, 9])

- isnan()

In [38]:
array_with_nan_values = np.array([1, 2, np.nan, 4])

np.isnan(array_with_nan_values)

array([False, False,  True, False])

# Exercícios

1) Escreva uma função que substitui todos os valores de um array (passado como argumento) que sejam inferiores a um número (também passado como argumento) por -100.

2) Escreva uma função que recebe um array com valores em falta como argumento e retorna as posições dos mesmos.

3) Escreva uma função que devolve uma matriz 3x3 com valores desde 2 até 10.

4) Escreva uma função que recebe um array como argumento cujos valores correspondem a graus centígrados e retorna a sua conversão para graus Fahrenheit.

In [ ]:
#type

In [ ]:
#forma e remodelaçao - rot90...

In [ ]:
#separacao - axis = 1...